apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sna
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sna
    app.kubernetes.io/part-of: sna
  name: sna
  namespace: ralphjbean
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: sna
status:
  loadBalancer: {}
